name: Build Kivy App to APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          sudo apt-get install -y zip unzip autoconf libtool pkg-config cmake
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
