name: Build Kivy App to APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          sudo apt-get install -y zip unzip autoconf libtool pkg-config
          pip install buildozer cython virtualenv

      # НАДЁЖНЫЙ КОСТЫЛЬ: Заранее создаем файлы лицензий, чтобы Android SDK не задавал вопросов
      - name: Pre-accept Android SDK Licenses
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n8933bad161ad4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb7437c3550b3118b726\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
