name: Build Kivy App to APK

# Сборка будет запускаться автоматически при загрузке кода в ветки main или master
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          sudo apt-get install -y zip unzip autoconf libtool pkg-config
          pip install buildozer cython virtualenv

      - name: Build APK with Buildozer
        # Процесс сборки (может занять 10-20 минут)
        run: |
          buildozer android debug

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          # Сохраняем готовый файл из папки bin
          path: bin/*.apk
